// Utilities
const NO = 0;
const YES = 1;

// Discount
const DISCOUNT_TYPE_AMOUNT = 1;
const DISCOUNT_TYPE_PERCENTAGE = 2;

// Customers
const CUSTOMER_STATUS_APPROVED = 1;
const CUSTOMER_STATUS_DECLINED = 2;
const CUSTOMER_STATUS_PENDING = 3;

// Product Images
const PRODUCT_IMAGES_TYPE_MAIN = 1;
const PRODUCT_IMAGES_TYPE_THUMBNAIL = 2;
const PRODUCT_IMAGES_TYPE_FEATURED = 3;
const PRODUCT_IMAGES_TYPE_FASH_DEAL = 4;

// Sales Orders
const SO_STATUS_CLOSED = 1;
const SO_STATUS_DELIVERED = 2;
const SO_STATUS_ON_PROCESS = 3;
const SO_STATUS_APPROVED = 4;
const SO_STATUS_REVIEWED = 5;
const SO_STATUS_OPEN = 6;
const SO_STATUS_CANCELLED = 7;
const SO_STATUS_FAILED = 8;

// Sales Orders Details
const SO_DETAILS_STATUS_CLAIMED = 1;
const SO_DETAILS_STATUS_ON_GOING = 2;
const SO_DETAILS_STATUS_PENDING = 3;
const SO_DETAILS_STATUS_RETURNED = 4;
const SO_DETAILS_STATUS_CANCELLED = 5;
const SO_DETAILS_STATUS_FAILED = 6;

module.exports = {
  NO,
  YES,
  DISCOUNT_TYPE_AMOUNT,
  DISCOUNT_TYPE_PERCENTAGE,
  CUSTOMER_STATUS_APPROVED,
  CUSTOMER_STATUS_DECLINED,
  CUSTOMER_STATUS_PENDING,
  PRODUCT_IMAGES_TYPE_MAIN,
  PRODUCT_IMAGES_TYPE_THUMBNAIL,
  PRODUCT_IMAGES_TYPE_FEATURED,
  PRODUCT_IMAGES_TYPE_FASH_DEAL,
  SO_STATUS_CLOSED,
  SO_STATUS_DELIVERED,
  SO_STATUS_ON_PROCESS,
  SO_STATUS_APPROVED,
  SO_STATUS_REVIEWED,
  SO_STATUS_OPEN,
  SO_STATUS_CANCELLED,
  SO_STATUS_FAILED,
  SO_DETAILS_STATUS_CLAIMED,
  SO_DETAILS_STATUS_ON_GOING,
  SO_DETAILS_STATUS_PENDING,
  SO_DETAILS_STATUS_RETURNED,
  SO_DETAILS_STATUS_CANCELLED,
  SO_DETAILS_STATUS_FAILED
};
