// Utilities
const NO = 0;
const YES = 1;

// Sales Orders
const SO_STATUS_CLOSED = 1;
const SO_STATUS_DELIVERED = 2;
const SO_STATUS_ON_PROCESS = 3;
const SO_STATUS_APPROVED = 4;
const SO_STATUS_REVIEWED = 5;
const SO_STATUS_OPEN = 6;
const SO_STATUS_CANCELLED = 7;
const SO_STATUS_FAILED = 8;

// Sales Orders Details
const SO_DETAILS_STATUS_CLAIMED = 1;
const SO_DETAILS_STATUS_ON_GOING = 2;
const SO_DETAILS_STATUS_PENDING = 3;
const SO_DETAILS_STATUS_RETURNED = 4;
const SO_DETAILS_STATUS_CANCELLED = 5;
const SO_DETAILS_STATUS_FAILED = 6;

module.exports = {
  NO,
  YES,
  SO_STATUS_CLOSED,
  SO_STATUS_DELIVERED,
  SO_STATUS_ON_PROCESS,
  SO_STATUS_APPROVED,
  SO_STATUS_REVIEWED,
  SO_STATUS_OPEN,
  SO_STATUS_CANCELLED,
  SO_STATUS_FAILED,
  SO_DETAILS_STATUS_CLAIMED,
  SO_DETAILS_STATUS_ON_GOING,
  SO_DETAILS_STATUS_PENDING,
  SO_DETAILS_STATUS_RETURNED,
  SO_DETAILS_STATUS_CANCELLED,
  SO_DETAILS_STATUS_FAILED
};
