const NO = 0;
const YES = 1;
const MALE = 1;
const FEMALE = 2;
const OTHER = 3;
const CUSTOMER_STATUS_APPROVED = 1;
const CUSTOMER_STATUS_DECLINED = 2;
const CUSTOMER_STATUS_PENDING = 3;
const RATE_TYPE_AMOUNT = 1;
const RATE_TYPE_PERCENTAGE = 2;
const CREDIT = 1;
const DEBIT = 2;
const PAYMENT_METHOD_CASH = 1;
const PAYMENT_METHOD_DEPOSIT = 2;
const PAYMENT_METHOD_CREDIT_CARD = 3;
const PAYMENT_METHOD_BANK_TRANSFER = 4;
const PAYMENT_METHOD_E_WALLET = 5;
const PAYMENT_METHOD_CHEQUE = 6;
const PAYMENT_METHOD_PDC = 7;
const SALES_ORDER_STATUS_CLOSED = 1;
const SALES_ORDER_STATUS_DELIVERED = 2;
const SALES_ORDER_STATUS_ON_PROCESS = 3;
const SALES_ORDER_STATUS_APPROVED = 4;
const SALES_ORDER_STATUS_REVIEWED = 5;
const SALES_ORDER_STATUS_OPEN = 6;
const SALES_ORDER_STATUS_CANCELLED = 7;
const SALES_ORDER_STATUS_FAILED = 8;
const CLAIM_TYPE_DELIVERY = 1;
const CLAIM_TYPE_PICK_UP = 2;

export {
  NO,
  YES,
  MALE,
  FEMALE,
  OTHER,
  CUSTOMER_STATUS_APPROVED,
  CUSTOMER_STATUS_DECLINED,
  CUSTOMER_STATUS_PENDING,
  RATE_TYPE_AMOUNT,
  RATE_TYPE_PERCENTAGE,
  CREDIT,
  DEBIT,
  PAYMENT_METHOD_CASH,
  PAYMENT_METHOD_DEPOSIT,
  PAYMENT_METHOD_CREDIT_CARD,
  PAYMENT_METHOD_BANK_TRANSFER,
  PAYMENT_METHOD_E_WALLET,
  PAYMENT_METHOD_CHEQUE,
  PAYMENT_METHOD_PDC,
  SALES_ORDER_STATUS_CLOSED,
  SALES_ORDER_STATUS_DELIVERED,
  SALES_ORDER_STATUS_ON_PROCESS,
  SALES_ORDER_STATUS_APPROVED,
  SALES_ORDER_STATUS_REVIEWED,
  SALES_ORDER_STATUS_OPEN,
  SALES_ORDER_STATUS_CANCELLED,
  SALES_ORDER_STATUS_FAILED,
  CLAIM_TYPE_DELIVERY,
  CLAIM_TYPE_PICK_UP,
};
