const STATUS_CLOSED = 1;
const STATUS_DELIVERED = 2;
const STATUS_ON_PROCESS = 3;
const STATUS_APPROVED = 4;
const STATUS_FOR_REVIEW = 5;
const STATUS_OPEN = 6;
const STATUS_CANCELLED = 7;
const STATUS_FAILED = 8;

export {
    STATUS_CLOSED,
    STATUS_DELIVERED,
    STATUS_ON_PROCESS,
    STATUS_APPROVED,
    STATUS_FOR_REVIEW,
    STATUS_OPEN,
    STATUS_CANCELLED,
    STATUS_FAILED,
}