var express = require("express");
var router = express.Router();
const { ErrorHandler } = require("../helpers/response-helper");

router.use("/authorizations", require("./authorizations"));
router.use("/roles", require("./roles"));
router.use("/users", require("./users"));
router.use("/banks", require("./banks"));
router.use("/customerBalance", require("./customerBalance"));
router.use("/customerCreditDebitCards", require("./customerCreditDebitCards"));
router.use("/customers", require("./customers"));
router.use("/employees", require("./employees"));
router.use("/frontendPolicyPages", require("./frontendPolicyPages"));
router.use("/frontendSliderImages", require("./frontendSliderImages"));
router.use("/frontendUsefulLinks", require("./frontendUsefulLinks"));
router.use("/inventories", require("./inventories"));
router.use("/inventoryHistories", require("./inventoryHistories"));
router.use("/payments", require("./payments"));
router.use("/productBrands", require("./productBrands"));
router.use("/productCategories", require("./productCategories"));
router.use("/productSubCategories", require("./productSubCategories"));
router.use("/productSubSubCategories", require("./productSubSubCategories"));
router.use("/products", require("./products"));
router.use("/productStores", require("./productStores"));
router.use("/productVariants", require("./productVariants"));
router.use("/productVariationDetails", require("./productVariationDetails"));
router.use("/productVariations", require("./productVariations"));
router.use("/productImages", require("./productImages"));
router.use("/productFlashDeals", require("./productFlashDeals"));
router.use("/productFlashDealDetails", require("./productFlashDealDetails"));
router.use("/salesOrderDetails", require("./salesOrderDetails"));
router.use("/salesOrders", require("./salesOrders"));
router.use("/salesOrderShippingDetails", require("./salesOrderShippingDetails"));
router.use("/shippingMethods", require("./shippingMethods"));
router.use("/shippingMethodRates", require("./shippingMethodRates"));
router.use((req, res, next) => {
  if (!req.route) return next(new ErrorHandler(404, []));
  next();
});

module.exports = router;
