var express = require('express');
var router = express.Router();

router.use('/authorizations', require('./authorizations'));
router.use('/roles', require('./roles'));
router.use('/users', require('./users'));
router.use('/banks', require('./banks'));
router.use('/customerCreditDebitCards', require('./customerCreditDebitCards'));
router.use('/customers', require('./customers'));
router.use('/employees', require('./employees'));
router.use('/frontendPolicyPages', require('./frontendPolicyPages'));
router.use('/frontendSliderImages', require('./frontendSliderImages'));
router.use('/frontendUsefulLinks', require('./frontendUsefulLinks'));
router.use('/inventories', require('./inventories'));
router.use('/inventoryHistories', require('./inventoryHistories'));
router.use('/productBrands', require('./productBrands'));
router.use('/productCategories', require('./productCategories'));
router.use('/productSubCategories', require('./productSubCategories'));
router.use('/productSubSubCategories', require('./productSubSubCategories'));
router.use('/products', require('./products'));
router.use('/productStores', require('./productStores'));
router.use('/productVariationDetails', require('./productVariationDetails'));
router.use('/productVariations', require('./productVariations'));
router.use('/productImages', require('./productImages'));
router.use('/productOptions', require('./productOptions'));
router.use('/productFlashDealHeaders', require('./productFlashDealHeaders'));
router.use('/productFlashDealDetails', require('./productFlashDealDetails'));
router.use('/salesOrderDetails', require('./salesOrderDetails'));
router.use('/salesOrders', require('./salesOrders'));
router.use('/shippingMethods', require('./shippingMethods'));
router.use('/shippingMethodRates', require('./shippingMethodRates'));

module.exports = router;
